/**
 * sw.js
 *
 * Atomic, versioned offline cache for Percussion Studio.
 *
 * Model (see docs/requirements/offline-updates.md):
 * - `precache.json` (generated by tools/generate_manifest.py) describes one
 *   complete app snapshot: a content version plus every asset with its
 *   SHA-256. The version changes iff any shipped file changes.
 * - The worker builds the snapshot into `ps-v<version>` atomically: every
 *   asset is downloaded (or reused from the previous snapshot by matching
 *   hash), hash-verified, and only when the whole set verifies is it made
 *   active and the previous snapshot deleted. A running page therefore
 *   always sees exactly one coherent version, online and offline.
 * - Fetches for snapshot paths are served cache-first from the active
 *   version; everything else (non-GET, cross-origin, unknown paths) passes
 *   through. `sw.js` and `precache.json` are never cached here.
 * - Update checks happen on navigation (throttled) and on demand via a
 *   `{ type: 'ps-check-update' }` message; clients are notified with
 *   `{ type: 'app-version-ready', version }` and the page decides when to
 *   reload (deferred while playing).
 */

const PRECACHE_URL = 'precache.json';
const CACHE_PREFIX = 'ps-v';
const META_DB = 'ps-sw-meta';
const META_STORE = 'meta';
const META_KEY = 'activeManifest';
const CHECK_THROTTLE_MS = 5 * 60 * 1000;
const BUILD_CONCURRENCY = 6;

const scopeUrl = new URL(self.registration.scope);

/** Absolute href for a snapshot-relative path (e.g. "data/sounds/x.wav"). */
const assetHref = (path) => new URL(path, scopeUrl).href;

/** URL pathname for a snapshot-relative path, used as the lookup key. */
const assetPathname = (path) => new URL(path, scopeUrl).pathname;

/** @type {{version: string, assets: Array<{path: string, hash: string}>}|null} */
let activeManifest = null;
/** @type {Map<string, {path: string, hash: string}>} */
let assetByPathname = new Map();
let readyPromise = null;
let buildPromise = null;
let lastCheckAt = 0;

// ─── IndexedDB (active manifest survives service worker restarts) ──────────

const openMeta = () => new Promise((resolve, reject) => {
    const request = indexedDB.open(META_DB, 1);
    request.onupgradeneeded = () => request.result.createObjectStore(META_STORE);
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
});

const metaGet = async (key) => {
    const db = await openMeta();
    return new Promise((resolve, reject) => {
        const request = db.transaction(META_STORE, 'readonly').objectStore(META_STORE).get(key);
        request.onsuccess = () => resolve(request.result ?? null);
        request.onerror = () => reject(request.error);
    });
};

const metaSet = async (key, value) => {
    const db = await openMeta();
    return new Promise((resolve, reject) => {
        const tx = db.transaction(META_STORE, 'readwrite');
        tx.objectStore(META_STORE).put(value, key);
        tx.oncomplete = () => resolve();
        tx.onerror = () => reject(tx.error);
    });
};

// ─── State ─────────────────────────────────────────────────────────────────

const indexAssets = () => {
    assetByPathname = new Map();
    if (!activeManifest || !Array.isArray(activeManifest.assets)) return;
    for (const asset of activeManifest.assets) {
        assetByPathname.set(assetPathname(asset.path), asset);
    }
};

const getReady = () => {
    if (!readyPromise) {
        readyPromise = (async () => {
            try {
                const stored = await metaGet(META_KEY);
                if (!stored || !stored.version) return null;
                const cacheNames = await caches.keys();
                if (!cacheNames.includes(CACHE_PREFIX + stored.version)) return null;
                activeManifest = stored;
                indexAssets();
                return stored.version;
            } catch {
                return null;
            }
        })();
    }
    return readyPromise;
};

const sha256Hex = async (buffer) => {
    const digest = await crypto.subtle.digest('SHA-256', buffer);
    return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
};

// Only a clean Content-Type is stored: copying the upstream headers would
// preserve `Content-Encoding: gzip` on the already-decoded body (GitHub Pages
// compresses assets), corrupting every cached response.
const CONTENT_TYPES = {
    js: 'text/javascript', mjs: 'text/javascript', json: 'application/json',
    html: 'text/html', css: 'text/css', svg: 'image/svg+xml', wav: 'audio/wav',
    yaml: 'text/yaml', yml: 'text/yaml', png: 'image/png', ico: 'image/x-icon',
    md: 'text/markdown', txt: 'text/plain',
};

const contentTypeFor = (path) => {
    const extension = path.split('.').pop()?.toLowerCase();
    return CONTENT_TYPES[extension] || 'application/octet-stream';
};

const cacheResponse = (buffer, contentType) => new Response(buffer, {
    status: 200,
    statusText: 'OK',
    headers: { 'Content-Type': contentType },
});

const notifyClients = async (version) => {
    const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of clients) {
        client.postMessage({ type: 'app-version-ready', version });
    }
};

// ─── Atomic snapshot build ─────────────────────────────────────────────────

const runPool = async (items, worker, concurrency = BUILD_CONCURRENCY) => {
    const queue = [...items];
    const workers = Array.from({ length: Math.min(concurrency, queue.length) }, () => (async () => {
        while (queue.length > 0) {
            await worker(queue.shift());
        }
    })());
    await Promise.all(workers);
};

const doBuild = async (precache) => {
    const newCacheName = CACHE_PREFIX + precache.version;
    if (activeManifest?.version === precache.version) return precache.version;

    const oldCacheName = activeManifest ? CACHE_PREFIX + activeManifest.version : null;
    const oldCache = oldCacheName ? await caches.open(oldCacheName) : null;
    const newCache = await caches.open(newCacheName);

    try {
        await runPool(precache.assets, async (asset) => {
            const href = assetHref(asset.path);

            // Reuse the identical asset from the previous snapshot: no download.
            if (oldCache) {
                const hit = await oldCache.match(href);
                if (hit) {
                    const buffer = await hit.clone().arrayBuffer();
                    if (await sha256Hex(buffer) === asset.hash) {
                        const contentType = hit.headers.get('content-type') || contentTypeFor(asset.path);
                        await newCache.put(href, cacheResponse(buffer, contentType));
                        return;
                    }
                }
            }

            // Fresh download, bypassing the HTTP cache so the byte content is
            // exactly the deployed one.
            const response = await fetch(href, { cache: 'reload' });
            if (!response.ok) throw new Error(`HTTP ${response.status} for ${asset.path}`);
            const buffer = await response.arrayBuffer();
            if (await sha256Hex(buffer) !== asset.hash) {
                throw new Error(`Hash mismatch for ${asset.path}`);
            }
            const contentType = response.headers.get('content-type') || contentTypeFor(asset.path);
            await newCache.put(href, cacheResponse(buffer, contentType));
        });

        // Commit only after every asset verified.
        activeManifest = { version: precache.version, assets: precache.assets };
        indexAssets();
        try {
            await metaSet(META_KEY, activeManifest);
        } catch {
            /* IDB unavailable: the cache still works for this worker instance */
        }
        for (const name of await caches.keys()) {
            if (name.startsWith(CACHE_PREFIX) && name !== newCacheName) {
                try { await caches.delete(name); } catch { /* best effort */ }
            }
        }
        return precache.version;
    } catch (error) {
        console.warn('[SW] snapshot build failed:', error);
        try { await caches.delete(newCacheName); } catch { /* best effort */ }
        return null;
    }
};

const buildSnapshot = (precache) => {
    if (!buildPromise) {
        buildPromise = doBuild(precache).finally(() => { buildPromise = null; });
    }
    return buildPromise;
};

const checkForUpdate = async (force = false) => {
    const now = Date.now();
    if (!force && now - lastCheckAt < CHECK_THROTTLE_MS) return;
    lastCheckAt = now;

    try {
        await getReady();
        // `no-store` + timestamp bypass both the browser and edge caches.
        const response = await fetch(`${PRECACHE_URL}?ts=${now}`, { cache: 'no-store' });
        if (!response.ok) return;
        const precache = await response.json();
        if (!precache?.version || !Array.isArray(precache.assets)) return;
        if (precache.version === activeManifest?.version) return;

        const version = await buildSnapshot(precache);
        if (version) await notifyClients(version);
    } catch {
        /* offline or malformed: keep the active snapshot */
    }
};

// ─── Fetch serving ─────────────────────────────────────────────────────────

const lookupAsset = (pathname) => {
    const direct = assetByPathname.get(pathname);
    if (direct) return direct;
    if (pathname.endsWith('/')) return assetByPathname.get(`${pathname}index.html`) || null;
    return null;
};

const handleFetch = async (event, request, url) => {
    await getReady();

    if (request.mode === 'navigate') {
        event.waitUntil(checkForUpdate());
    }

    const asset = lookupAsset(url.pathname);
    if (!activeManifest || !asset) {
        return fetch(request);
    }

    const cache = await caches.open(CACHE_PREFIX + activeManifest.version);
    const hit = await cache.match(assetHref(asset.path));
    return hit || fetch(request);
};

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;

    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    const pathname = url.pathname;
    if (pathname === assetPathname('sw.js') || pathname === assetPathname(PRECACHE_URL)) return;

    event.respondWith(handleFetch(event, request, url));
});

// ─── Lifecycle ─────────────────────────────────────────────────────────────

self.addEventListener('install', () => {
    self.skipWaiting();
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        await self.clients.claim();
        await checkForUpdate(true);
    })());
});

self.addEventListener('message', (event) => {
    if (event.data?.type === 'ps-check-update') {
        event.waitUntil(checkForUpdate(true));
    }
});
